import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { PageHeader, LinkListCard } from '@/components/molecules'
import { useRouter } from 'next/router'
import { Common as CommonLayout } from '@/components/layouts'
import { getAllGuidesByCategories } from '../../lib/graphql'

const Page: NextPage = ({ guideCategories, guides }: any) => {
  const router = useRouter()
  const [searchString, setSearchString] = useState('')

  return (
    <>
      <Head>
        <title>Tesla Guides - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container flex'>
          <PageHeader
            hasSearch
            heading='Written by Tesla Owners <br /> for Tesla Owners'
            description={`Search through over ${guides?.pageInfo?.total} ${
              guides?.pageInfo?.total > 1 ? 'guides' : 'guide'
            }`}
            // image='https://images.unsplash.com/flagged/photo-1579782647395-2e6fb36a64f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=806&q=80'
            btnProps={{
              onClick: (e: any) => {
                e.preventDefault()
                router.push(`/guides/search/?q="${searchString}"`)
              },
              children: 'Search',
              appearance: 'primary',
            }}
            inputProps={{
              onChange: (e: any) => setSearchString(e.target.value),
              placeholder: 'Search a guide',
              value: searchString,
              size: 'lg',
              onKeyDown: (event: any) => {
                if (event.key === 'Enter') {
                  router.push(`/guides/search/?q="${searchString}"`)
                }
              },
            }}
          />
        </div>

        <div className='container flex flex-col gap-[24px] pt-[24px] pb-[40px] md:gap-[40px] md:py-[40px]'>
          <h4 className='text-h4 font-600 text-N-800'>Browse guides by category</h4>

          <div className='flex flex-col gap-[24px] md:grid md:grid-cols-2 md:gap-[32px]'>
            {guideCategories.map(({ name, slug, guides }: any, index: number) => (
              <LinkListCard
                key={slug || index}
                list={guides.nodes}
                heading={name}
                articleCount={guides.nodes.length}
                link={`/guides/category/${slug}`}
              />
            ))}
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ preview = false, previewData }: any) {
  const data = await getAllGuidesByCategories()

  return {
    props: {
      preview,
      guideCategories: data?.guideCategories?.nodes,
      guides: data?.guides,
    },
    
  }
}

export default Page
