import type { NextPage } from 'next'
import CN from 'classnames'
import Link from 'next/link'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { Button } from '@/components/atoms'
import { PageHeader, SectionHeading } from '@/components/molecules'
import { ArrowRight, ChevronRight } from 'react-feather'
import { Chip } from '@/components/atoms'
import { useViewport } from '@/utils'
import { Common as CommonLayout } from '@/components/layouts'

import { getRegion, getAllRegionsWithSlug } from '../../lib/graphql'

const Page: NextPage = ({ regions }: any) => {
  const { isDesktop, isMobile, isTablet } = useViewport()

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container pt-[24px] md:pt-[40px] lg:pt-[40px]'>
          <div className='h-[114px] justify-center bg-none bg-cover bg-no-repeat md:flex md:bg-[url(/images/regions-md.png)] lg:flex lg:h-[272px] lg:bg-[url(/images/regions.png)]'>
            <div className='flex flex-col items-center justify-center gap-[16px] text-center'>
              <h1 className='text-h3 font-700 text-N-800 md:text-h2 lg:text-h1'>Regions</h1>
              <p className='text-md font-500 text-N-600 md:w-[368px] lg:w-[368px]'>
                Regions allow owners to meet up and discuss on a more local level, all region groups
                are supported by Tesla Owners UK and Tesla.
              </p>
            </div>
          </div>
          {isMobile && (
            <div className='pt-[40px]'>
              <img src='/images/regions-small.png' className='w-full' />
            </div>
          )}

          <div className='region-list py-[40px] md:py-[80px]'>
            <ul className='flex flex-col gap-[24px] md:flex md:px-[88px] lg:grid lg:grid-cols-3 lg:gap-x-[48px] lg:gap-y-[24px] lg:px-0'>
              {(regions || [])?.map(({ slug, title }: any, index: number) => (
                <li key={slug || index}>
                  <Link href={`/regions/${slug}`}>
                    <a
                      className={CN(
                        `group flex items-center justify-between text-N-800 hover:text-B-500`
                      )}>
                      <h5 className={CN(`text-base group-hover:text-B-500`)}>{title}</h5>
                      <span>{<ChevronRight size={24} />}</span>
                    </a>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ params, preview = false, previewData }: any) {
  const allRegions = await getAllRegionsWithSlug()

  return {
    props: {
      preview,
      regions: allRegions?.nodes,
    },
    revalidate: 1,
  }
}

export default Page
