import CN from 'classnames'
import Link from 'next/link'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Button, CheckBox } from '@/components/atoms'
import { DashboardMenu } from '@/components/molecules/DashboardMenu'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = () => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container gap-[48px] pb-[40px] lg:grid lg:grid-cols-[160px_5fr] lg:pb-[80px]'>
          <div className='dashboard-menu hidden lg:flex'>
            <div className='w-full'>
              <DashboardMenu />
            </div>
          </div>

          <div className='flex w-full flex-col'>
            <h4 className='text-h4 font-600 text-N-800'>Email alerts (Subscriptions)</h4>

            <div className='personal-details w-full pt-[24px]'>
              <div className='text-md font-400 text-N-600'>
                <p>Alert me for following topics.</p>
              </div>

              <div className='flex flex-col pt-[40px] md:flex-row md:gap-[104px] lg:flex-row lg:gap-[104px]'>
                <div className='flex flex-col gap-[24px] text-base font-600 text-N-600'>
                  <CheckBox>School Show and Tell Events Nearby</CheckBox>
                  <CheckBox>Tesla New Owner Support</CheckBox>
                  <CheckBox>Home & Work</CheckBox>
                  <CheckBox>Charger Installer</CheckBox>
                  <CheckBox>Solar</CheckBox>
                </div>
              </div>

              <div className='save-button pt-[24px] md:pt-[40px] lg:pt-[40px]'>
                <Button
                  className='w-full text-base !font-600 !text-N-800 md:w-[unset] lg:w-[unset]'
                  appearance='secondary'>
                  Save changes
                </Button>
              </div>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
