import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Tag, ArrowLeft, Globe, MapPin, Phone, Mail, Bookmark, Compass } from 'react-feather'
import { useViewport } from '@/utils'
import { SupplierAboutHeader } from '@/components/molecules/SupplierAboutHeader'
import { Button, TextField } from '@/components/atoms'
import { SupplierDetailsTabs } from '@/components/sections/SupplierDetailsTabs'
import { SupplierAboutSideBar } from '@/components/sections/SupplierAboutSideBar'
import { RelatedListingsSideBar } from '@/components/sections/RelatedListingsSideBar'
import { Breadcrumb } from '@/components/molecules/Breadcrumb'

import { getAllSuppliersWithSlug, getSupplier } from '../../lib/graphql'
import Link from 'next/link'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = ({ supplier }: any) => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()
  const [activeTab, setActiveTab] = useState('about')

  const { title, supplierTags, pageSupplier } = supplier || {}
  const {
    address,
    description,
    email,
    isFeatured,
    isVerified,
    location,
    logo,
    name,
    phone,
    rating,
    website,
  } = pageSupplier || {}

  return (
    <>
      <Head>
        <title>{`${title || 'Supplier'}`} - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='header-surface relative bg-[url(/images/004.svg)] bg-cover bg-no-repeat'>
          <div className='container flex h-full flex-col'>
            <div className='flex py-[50px]'>
              <Link href='/suppliers' passHref>
                <Button
                  appearance='ghost'
                  iconBefore={<ArrowLeft size={20} />}
                  className='h-[unset] px-0 hover:text-B-500'>
                  Back to Suppliers list
                </Button>
              </Link>
            </div>

            <SupplierAboutHeader
              icon={<Tag size={16} />}
              breadcrumbLinks={<Breadcrumb links={supplierTags?.nodes} />}
              heading={title}
              isVerified={isVerified}
              isFeatured={isFeatured}
              image={logo?.mediaItemUrl}
              rating={rating}
            />
          </div>
        </div>

        <div className='container flex flex-col gap-[24px] pt-[24px] pb-[40px] md:gap-[48px] md:pt-[40px] md:pb-[80px] lg:flex-row'>
          <div className='lg:w-[784px]'>
            <SupplierDetailsTabs data={supplier} onChange={(tab: any) => setActiveTab(tab)} />
          </div>

          <div className='flex'>
            {activeTab === 'about' && <SupplierAboutSideBar data={supplier} />}
            {/* {activeTab === 'related-listings' && <RelatedListingsSideBar data={supplier} />} */}
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ params, preview = false, previewData }: any) {
  const data = await getSupplier(params.slug || '')

  return {
    props: {
      preview,
      supplier: data.supplier,
    },
    
  }
}

export async function getStaticPaths() {
  const allSuppliers = await getAllSuppliersWithSlug()

  return {
    paths: allSuppliers?.edges.map(({ node }: any) => `/suppliers/${node.slug}`) || [],
    fallback: true,
  }
}

export default Page
