import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { PageHeaderVariant } from '@/components/molecules/PageHeaderVariant'
import { Button, TextField, Badge } from '@/components/atoms'
import { Pagination, SectionHeading } from '@/components/molecules'
import { ArrowRight, Search } from 'react-feather'
import { SearchSuppliers, SuppliersSearch } from '@/components/molecules'
import { supplierList } from '@/dummy-data/supplier-list'
import { useViewport } from '@/utils'
import parseHTML from 'html-react-parser'
import { useQuery, gql } from '@apollo/client'

import { getSuppliersPage, SEARCH_SUPPLIERS } from '../../lib/graphql'
import Link from 'next/link'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = ({ pageData, isServer }: any) => {
  const router = useRouter()
  console.log(`${router.pathname} - Is this page on the server? - ${isServer ? 'YES' : 'NO'}`)

  const { isMobile, isTablet, isDesktop } = useViewport()
  const { header, keyPartners, verifiedSuppliers, suppliers, footer } = pageData || {}

  return (
    <>
      <Head>
        <title>Supplier Directory - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <CommonLayout>
        <div className='container flex pt-[40px] pb-[24px]'>
          <div className='mx-auto flex w-full max-w-[782px] flex-col items-center gap-[40px] text-center'>
            <div className='flex w-full flex-col gap-[20px]'>
              <div className='flex justify-center'>
                <Badge>Tesla Owners UK Initiative</Badge>
              </div>
              <h1 className='text-h1'>Become a supplier</h1>
            </div>

            <div className='banner-image flex w-full'>
              {/* <img
                src={initiative?.pageInitiativeSidebar?.thumbnail?.mediaItemUrl}
                alt={initiative?.title}
                className='w-[100%] rounded-[8px]'
              /> */}
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const pageData = await getSuppliersPage()

  return {
    props: {
      pageData,
    },
  }
}

export default Page
