import type { NextPage } from 'next'
import Head from 'next/head'
import { ExpandedProductDetails } from '@/components/sections/ExpandedProductDetails'
import { Common as CommonLayout } from '@/components/layouts'
import { ShopVideos, ShopDetails } from '@/components/sections'
import { Button } from '@/components/atoms'
import { ArrowRight } from 'react-feather'
import { ShopCard } from '@/components/molecules/ShopCard'

import { getProduct, getProducts } from '../../lib/graphql'

const Page: NextPage = ({ product }: any) => {
  const shopListA = [
    {
      id: 0,
      image: '/shop-item.png',
      heading: 'Charging Cable (EU+UK) Rental Set',
      price: '£6.00',
      shopName: 'Milton Keynes Team',
      url: '#',
    },
    {
      id: 1,
      image: '/shop-item.png',
      heading: 'Charging Cable (EU+UK) Rental Set',
      price: '£6.00',
      shopName: 'Milton Keynes Team',
      url: '#',
    },
    {
      id: 2,
      image: '/shop-item.png',
      heading: 'Charging Cable (EU+UK) Rental Set',
      price: '£6.00',
      shopName: 'Milton Keynes Team',
      url: '#',
    },
    {
      id: 3,
      image: '/shop-item.png',
      heading: 'Charging Cable (EU+UK) Rental Set',
      price: '£6.00',
      shopName: 'Milton Keynes Team',
      url: '#',
    },
  ]

  console.log(product)

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container pt-[24px] md:pb-[80px]'>
          <ExpandedProductDetails product={product} />

          <div className='pt-[60px]' id='description'>
            <ShopDetails product={product} />
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ params, preview = false, previewData }: any) {
  const data = await getProduct(params.slug)

  return {
    props: {
      preview,
      product: data,
    },
    revalidate: 1,
  }
}

export async function getStaticPaths() {
  const allProducts = await getProducts()

  console.log(allProducts)

  return {
    paths: allProducts?.nodes?.map(({ slug }: any) => `/shop/${slug}`) || [],
    fallback: true,
  }
}

export default Page
