import { useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useViewport } from '@/utils'
import { Button, CheckBox, TextField } from '@/components/atoms'
import { CheckoutCard } from '@/components/molecules/CheckoutCard'
import { PaymentGateway } from '@/components/sections/PaymentGateway'
import { AddressCard } from '@/components/molecules/AddressCard'

import { Common as CommonLayout } from '@/components/layouts'

import { useAppContext } from '@/context'

const Page: NextPage = () => {
  const { isMobile, isTablet, isDesktop } = useViewport()
  const { sidemenu, header, footer, suppliers, user, fullUser, isLoading, cart }: any =
    useAppContext()

  useEffect(() => {
    console.log(cart)
  }, [cart])

  return (
    <>
      <Head>
        <title>Checkout - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container'>
          <div className='flex flex-col pb-[24px] md:pb-[40px]'>
            <h1 className='text-h4 font-600 text-N-800 md:text-h3 md:font-700'>Checkout</h1>
          </div>

          <div className='grid grid-cols-[7fr_2fr] gap-[32px]'>
            <CheckoutCard />

            <div className='w-full pb-[40px] md:pb-[80px]'>
              {/* Addresses */}
              <div className='flex flex-col gap-[32px]'>
                <AddressCard
                  heading='Billing address'
                  type='billing'
                  name={`${fullUser?.customer?.billing?.firstName} ${fullUser?.customer?.billing?.lastName}`}
                  address={`
                  ${fullUser?.customer?.billing?.address1 || ''} <br />
                  ${fullUser?.customer?.billing?.address2 || ''} <br />
                  ${fullUser?.customer?.billing?.city || ''} <br />
                  ${fullUser?.customer?.billing?.postcode || ''} <br />
                  ${fullUser?.customer?.billing?.state || ''}
                  `}
                  phoneNumber={fullUser?.customer?.billing?.phone}
                  email={fullUser?.customer?.billing?.email}
                />

                <AddressCard
                  heading='Shipping address'
                  type='shipping'
                  name={`${fullUser?.customer?.shipping?.firstName} ${fullUser?.customer?.shipping?.lastName}`}
                  address={`
                  ${fullUser?.customer?.shipping?.address1 || ''} <br />
                  ${fullUser?.customer?.shipping?.address2 || ''} <br />
                  ${fullUser?.customer?.shipping?.city || ''} <br />
                  ${fullUser?.customer?.shipping?.postcode || ''} <br />
                  ${fullUser?.customer?.shipping?.state || ''}
                  `}
                  phoneNumber={fullUser?.customer?.shipping?.phone}
                  email={fullUser?.customer?.shipping?.email}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Bank details, Payment methods */}
        <div className='container'>
          <div className='py-[40px] md:py-[40px]'>
            <h4 className='text-h4 font-600 text-N-800'>Payment method</h4>

            <div className='flex flex-col gap-[16px] pt-[24px] md:grid md:grid-cols-2 md:gap-[24px] lg:flex lg:flex-row lg:gap-[48px] lg:pt-[40px]'>
              {/* Payment method */}
              <PaymentGateway />

              {/* Place order button */}
              <div className='flex flex-col gap-[24px]'>
                <div className='flex flex-col gap-[16px]'>
                  <p className='text-base font-400 text-N-800'>
                    Your personal data will be used to process your order, support your experience
                    throughout this website, and for other purposes described in our privacy policy.
                  </p>

                  {/* This checkbox does not appear in the direct debit page version */}
                  <div className='flex items-center gap-[12px]'>
                    <CheckBox />
                    <p className='text-base font-400'>
                      I have read and agree to the website {''}
                      <a href='#' target='_blank' className='text-base font-600'>
                        terms and conditions {''}
                      </a>
                      <span className='text-base text-B-500'>*</span>
                    </p>
                  </div>
                </div>
                <div className='flex'>
                  <Button className='w-full lg:w-[unset]'>Place order</Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
