import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Confetti from 'react-confetti'

import useWindowSize from 'react-use/lib/useWindowSize'

import { Button } from '@/components/atoms'
import { PagePlaceholder } from '@/components/molecules'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = () => {
  const { width, height } = useWindowSize()
  const [runConfetti, setRunConfetti] = useState(false)

  return (
    <>
      <Head>
        <title>Order successfull - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <Confetti width={width} height={height} run={true} recycle={runConfetti} />

        <div className='container'>
          <PagePlaceholder
            heading='Order Successful'
            description={
              <div className='max-w-[600px]'>
                Your order is placed successfully. You will receive an <br />
                email with the order details.
              </div>
            }
            cta={
              <Link href='/account/purchases'>
                <Button appearance='primary'>View your order status</Button>
              </Link>
            }
          />
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
