import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { Button } from '@/components/atoms'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Page not found - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container py-[24px]'>
          <div className='flex flex-col items-center rounded-[8px] bg-white py-[48px] px-[16px] shadow-card-shadow md:py-[80px] md:px-[64px] lg:px-0'>
            {/* <img src='/images/error-image.png' className='w-[312px]' /> */}
            <h2 className='pt-[20px] text-h3 font-700 text-N-800 md:text-h2 lg:text-h2'>
              Order Success
            </h2>
            <p className='w-full pt-[16px] text-center text-md text-N-600 lg:w-[46%]'>Noice!</p>
            <div className='w-full pt-[32px]  md:w-[unset] lg:w-[unset]'>
              <Link href='/'>
                <Button
                  className='w-full text-base !font-600 md:w-[unset] lg:w-[unset]'
                  appearance='primary'>
                  Back to home page
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
