export const shopList = [
  {
    id: 0,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 1,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 2,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 3,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 4,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 5,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 6,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 7,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
  {
    id: 8,
    image: '/shop-item.png',
    heading: 'Charging Cable (EU+UK) Rental Set',
    price: '£6.00',
    shopName: 'Milton Keynes Team',
    url: '#',
  },
]

export default shopList
