import type { NextPage } from 'next'
import CN from 'classnames'
import Link from 'next/link'
import Head from 'next/head'
import _ from 'lodash'

import { useState, useEffect } from 'react'
import { useMutation, useQuery } from '@apollo/client'
import { useRouter } from 'next/router'
import { useAppContext } from '@/context'

import { toast } from '@/components/molecules'
import { Button, CheckBox, TextField } from '@/components/atoms'
import { DashboardMenu } from '@/components/molecules/DashboardMenu'
import { Common as CommonLayout } from '@/components/layouts'

import { UPDATE_SHIPPING } from '../../../lib/graphql'

const Page: NextPage = () => {
  const router = useRouter()
  const { fullUser, user, userOrders, refetchUser, fetchFullUser }: any = useAppContext()
  const addressesAreEqual =
    _.isEqual(fullUser?.customer?.billing?.address1, fullUser?.customer?.shipping?.address1) ||
    false
  const [useBillingAddressForShipping, setUseBillingAddressForShipping] =
    useState(addressesAreEqual)

  const billingAddress = {
    id: user?.id,
    address1: fullUser?.customer?.billing?.address1,
    address2: fullUser?.customer?.billing?.address2,
    city: fullUser?.customer?.billing?.city,
    company: fullUser?.customer?.billing?.company,
    country: fullUser?.customer?.billing?.country,
    email: fullUser?.customer?.billing?.email,
    firstName: fullUser?.customer?.billing?.firstName,
    lastName: fullUser?.customer?.billing?.lastName,
    phone: fullUser?.customer?.billing?.phone,
    postcode: fullUser?.customer?.billing?.postcode,
    state: fullUser?.customer?.billing?.state,
  }

  const [updateShipping, { loading: loadingUpdateShipping }] = useMutation(UPDATE_SHIPPING, {
    variables: billingAddress,
  })

  useEffect(() => {
    if (user && user?.id) {
      fetchFullUser()
    }
  }, [user])

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container gap-[48px] pb-[40px] lg:grid lg:grid-cols-[160px_5fr] lg:pb-[80px]'>
          <div className='dashboard-menu hidden lg:flex'>
            <div className='w-full'>
              <DashboardMenu />
            </div>
          </div>

          <div className='flex w-full flex-col'>
            <h4 className='text-h4 font-600 text-N-800'>Manage Account</h4>

            <div className='personal-details w-full pt-[24px]'>
              <div className='text-md font-400 text-N-600'>
                <p>The following addresses will be used on the checkout page by default.</p>
              </div>

              <div className='flex flex-col gap-[24px] pt-[24px] lg:gap-[40px] '>
                <div className='max-w-[482px] text-md font-500 text-N-800'>
                  <div className='pb-[16px]'>
                    <div className='billing-address-heading mb-[16px]'>
                      <p className='text-md font-500 text-N-800'>Billing address</p>
                    </div>

                    <div>
                      <h5 className='mb-[4px] text-base font-500 text-N-800'>
                        {fullUser?.customer?.firstName} {fullUser?.customer?.lastName}
                      </h5>
                      <div className='text-md font-400 text-N-800'>
                        <p>Address: {fullUser?.customer?.billing?.address1 || 'N/A'}</p>
                        <p>City: {fullUser?.customer?.billing?.city || 'N/A'}</p>
                        <p>Post Code: {fullUser?.customer?.billing?.postcode || 'N/A'}</p>
                        <p>Country: {fullUser?.customer?.billing?.country || 'N/A'}</p>
                        <p>Phone: {fullUser?.customer?.billing?.phone || 'N/A'}</p>
                        <p>Email: {fullUser?.customer?.billing?.email || 'N/A'}</p>
                      </div>
                    </div>
                  </div>

                  <Link href='/account/addresses/edit-billing'>
                    <Button appearance='secondary' size='sm'>
                      Edit billing address
                    </Button>
                  </Link>
                </div>

                <div className='max-w-[482px] text-md font-500 text-N-800'>
                  <div className='pb-[16px]'>
                    <div className='billing-address-heading mb-[16px]'>
                      <p className='text-md font-500 text-N-800'>Shipping address</p>
                    </div>

                    <div className='flex w-full flex-col gap-[4px] pb-[16px]'>
                      <CheckBox
                        defaultChecked={useBillingAddressForShipping}
                        children='Use same as billing address'
                        onChange={(e: any) => {
                          // setUseBillingAddressForShipping(e.target.checked)
                          if (e.target.checked === true) {
                            updateShipping()
                              .then(() => {
                                fetchFullUser()
                                  .then((res: any) => {})
                                  .catch((e: any) => {
                                    return toast({ message: e.message, type: 'error' })
                                  })
                              })
                              .catch()
                          } else {
                            setUseBillingAddressForShipping(false)
                          }
                        }}
                      />
                    </div>

                    {!useBillingAddressForShipping && (
                      <div>
                        <h5 className='mb-[4px] text-base font-500 text-N-800'>
                          {fullUser?.customer?.firstName} {fullUser?.customer?.lastName}
                        </h5>
                        <div className='text-md font-400 text-N-800'>
                          <p>Address: {fullUser?.customer?.shipping?.address1 || 'N/A'}</p>
                          <p>City: {fullUser?.customer?.shipping?.city || 'N/A'}</p>
                          <p>Post Code: {fullUser?.customer?.shipping?.postcode || 'N/A'}</p>
                          <p>Country: {fullUser?.customer?.shipping?.country || 'N/A'}</p>
                          <p>Phone: {fullUser?.customer?.shipping?.phone || 'N/A'}</p>
                        </div>
                      </div>
                    )}
                  </div>

                  {!useBillingAddressForShipping && (
                    <Link href='/account/addresses/edit-shipping'>
                      <Button appearance='secondary' size='sm'>
                        Edit shipping address
                      </Button>
                    </Link>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
