import type { NextPage } from 'next'
import CN from 'classnames'
import Link from 'next/link'
import Head from 'next/head'
import _ from 'lodash'

import { useState, useEffect } from 'react'
import { useMutation, useQuery } from '@apollo/client'
import { useRouter } from 'next/router'
import { useAppContext } from '@/context'

import { toast } from '@/components/molecules'
import { Button, CheckBox, TextField } from '@/components/atoms'
import { DashboardMenu } from '@/components/molecules/DashboardMenu'
import { Common as CommonLayout } from '@/components/layouts'

import { UPDATE_SHIPPING } from '../../../lib/graphql'

const Page: NextPage = () => {
  const router = useRouter()
  const { fullUser, user, userOrders, refetchUser, refetchFullUser }: any = useAppContext()
  const addressesAreEqual =
    _.isEqual(fullUser?.customer?.billing?.address1, fullUser?.customer?.shipping?.address1) ||
    false
  const [useBillingAddressForShipping, setUseBillingAddressForShipping] =
    useState(addressesAreEqual)

  const billingAddress = {
    id: user?.id,
    address1: fullUser?.customer?.billing?.address1,
    address2: fullUser?.customer?.billing?.address2,
    city: fullUser?.customer?.billing?.city,
    company: fullUser?.customer?.billing?.company,
    country: fullUser?.customer?.billing?.country,
    email: fullUser?.customer?.billing?.email,
    firstName: fullUser?.customer?.billing?.firstName,
    lastName: fullUser?.customer?.billing?.lastName,
    phone: fullUser?.customer?.billing?.phone,
    postcode: fullUser?.customer?.billing?.postcode,
    state: fullUser?.customer?.billing?.state,
  }

  const [updateShipping, { loading: loadingUpdateShipping }] = useMutation(UPDATE_SHIPPING, {
    variables: billingAddress,
  })

  useEffect(() => {
    if (user && user?.id) {
      refetchFullUser()
    }
  }, [user])

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container gap-[48px] pb-[40px] lg:grid lg:grid-cols-[160px_5fr] lg:pb-[80px]'>
          <div className='dashboard-menu hidden lg:flex'>
            <div className='w-full'>
              <DashboardMenu />
            </div>
          </div>

          <div className='flex w-full flex-col gap-[16px]'>
            <h4 className='text-h4 font-600 text-N-800'>Manage Addresses</h4>

            <div className='personal-details flex w-full flex-col gap-[32px]'>
              <div className='text-md text-N-600'>
                <p>The following addresses will be used on the checkout page by default.</p>
              </div>

              <div className='flex flex-col gap-[32px] '>
                <div className='flex max-w-[482px] flex-col gap-[16px]'>
                  <div className='flex flex-col gap-[16px]'>
                    <div className='billing-address-heading'>
                      <p className='text-md font-500 text-N-800'>Billing address</p>
                    </div>

                    <div className='flex flex-col'>
                      <h5 className='mb-[4px] text-base font-500 text-N-800'>
                        {fullUser?.customer?.billing?.firstName}{' '}
                        {fullUser?.customer?.billing?.lastName}
                      </h5>
                      <div className='text-md font-400 text-N-800'>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Address —</span>{' '}
                          {fullUser?.customer?.billing?.address1 || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>City —</span>{' '}
                          {fullUser?.customer?.billing?.city || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Postcode —</span>{' '}
                          {fullUser?.customer?.billing?.postcode || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>State —</span>{' '}
                          {fullUser?.customer?.billing?.state || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Phone —</span>{' '}
                          {fullUser?.customer?.billing?.phone || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Email —</span>{' '}
                          {fullUser?.customer?.billing?.email || '—'}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className='flex'>
                    <Link href='/account/addresses/edit-billing'>
                      <Button appearance='secondary' size='sm'>
                        Edit billing address
                      </Button>
                    </Link>
                  </div>
                </div>

                <div className='flex max-w-[482px] flex-col gap-[16px]'>
                  <div className='flex flex-col gap-[16px]'>
                    <div className='shipping-address-heading'>
                      <p className='text-md font-500 text-N-800'>Shipping address</p>
                    </div>

                    <div className='flex flex-col'>
                      <h5 className='mb-[4px] text-base font-500 text-N-800'>
                        {fullUser?.customer?.shipping?.firstName}{' '}
                        {fullUser?.customer?.shipping?.lastName}
                      </h5>
                      <div className='text-md font-400 text-N-800'>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Address —</span>{' '}
                          {fullUser?.customer?.shipping?.address1 || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>City —</span>{' '}
                          {fullUser?.customer?.shipping?.city || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Postcode —</span>{' '}
                          {fullUser?.customer?.shipping?.postcode || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>State —</span>{' '}
                          {fullUser?.customer?.shipping?.state || '—'}
                        </p>
                        <p className='flex items-center gap-[8px]'>
                          <span className='w-[100px]'>Phone —</span>{' '}
                          {fullUser?.customer?.shipping?.phone || '—'}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className='flex'>
                    <Link href='/account/addresses/edit-shipping'>
                      <Button appearance='secondary' size='sm'>
                        Edit shipping address
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
