import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { PageHeaderVariant } from '@/components/molecules/PageHeaderVariant'
import { Badge, Button, Chip, TextArea } from '@/components/atoms'
import { InitiativeCard } from '@/components/molecules/InitiativeCard'
import { ChartLine } from '@/icons'
import { LinkListCard, ListCard, SectionHeading } from '@/components/molecules'
import { Tag, ShoppingBag } from 'react-feather'
import { ArticleViewTopic } from '@/components/molecules/ArticleViewTopic'
import { InlineCTA } from '@/components/molecules/InlineCTA'

const Home: NextPage = () => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='header-surface relative min-h-[358px] bg-[url(/images/004.svg)] bg-cover bg-no-repeat'>
        <div className='absolute bottom-0 h-[240px] w-[60%] rounded-tr-[12px] bg-white' />
        <div className='z-1 relative top-[120px]'>
          <ArticleViewTopic
            icon={<Tag size={16} />}
            tagText='For new owners'
            heading='Must have accessories for your Tesla Model S'
            date='05/07/2021'
            readingTime='1 min'
          />
        </div>
      </div>

      <div className='container grid grid-cols-[680px_367px] gap-[150px]'>
        <div className='pt-[48px]'>
          <div className='flex gap-[48px]'>
            <div className='relative top-[12px] h-[4px] w-[56px] bg-B-500' />
            <article className='prose'>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua. Eget lorem dolor sed viverra ipsum
                nunc. Quam nulla porttitor massa id neque. Feugiat in ante metus dictum. Dignissim
                diam quis enim lobortis. Sagittis orci a scelerisque purus semper. Tincidunt
                praesent semper feugiat nibh sed pulvinar proin gravida. Neque convallis a cras
                semper auctor neque vitae tempus. Amet volutpat consequat mauris nunc congue nisi
                vitae suscipit. Nunc sed augue lacus viverra vitae congue eu consequat ac. Sit amet
                consectetur adipiscing elit. Vel pharetra vel turpis nunc. Tempor orci dapibus
                ultrices in iaculis. Imperdiet sed euismod nisi porta lorem.
                <br />
                <br />
                Venenatis tellus in metus vulputate. Suscipit tellus mauris a diam maecenas. Dolor
                sit amet consectetur adipiscing elit. Egestas diam in arcu cursus euismod quis. Quis
                risus sed vulputate odio ut enim blandit volutpat. Tortor consequat id porta nibh
                venenatis. Nisi porta lorem mollis aliquam. Ac orci phasellus egestas tellus rutrum
                tellus. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Mi
                bibendum neque egestas congue quisque egestas diam. Tempor id eu nisl nunc mi ipsum
                faucibus vitae aliquet. Dui accumsan sit amet nulla facilisi morbi tempus. Laoreet
                id donec ultrices tincidunt arcu non. In ante metus dictum at tempor. Sodales neque
                sodales ut etiam sit amet nisl purus. Odio aenean sed adipiscing diam.
              </p>
            </article>
          </div>
          <div className='h-[368px] w-[680px] pt-[40px]'>
            <img
              className='h-full w-full rounded-[12px] object-cover object-center'
              src='https://images.unsplash.com/photo-1617704548623-340376564e68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
            />
          </div>
          <article className='prose'>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Eget lorem dolor sed viverra ipsum nunc.
              Quam nulla porttitor massa id neque. Feugiat in ante metus dictum. Dignissim diam quis
              enim lobortis. Sagittis orci a scelerisque purus semper. Tincidunt praesent semper
              feugiat nibh sed pulvinar proin gravida. Neque convallis a cras semper auctor neque
              vitae tempus. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Nunc sed
              augue lacus viverra vitae congue eu consequat ac. Sit amet consectetur adipiscing
              elit. Vel pharetra vel turpis nunc. Tempor orci dapibus ultrices in iaculis. Imperdiet
              sed euismod nisi porta lorem.
            </p>
          </article>
          <LinkListCard
            heading='Products you may like on Amazon'
            list={[
              {
                id: 0,
                textIcon: <ShoppingBag size={20} />,
                text: 'Millaissolutions Car Detailing Valeters Wash and Rinse Two Bucket System - 20 litre Buckets **LIMITED TIME - NOW SUPPLIED WITH SCATCHSHIELD GUARDS **',
              },
              {
                id: 1,
                textIcon: <ShoppingBag size={20} />,
                text: 'Set of 2 Buckets and Grit Guards, Premium Quality, Prevent Swirls and Scratches when Washing Your Car, 20 Litre Buckets with Lids',
              },
              {
                id: 2,
                textIcon: <ShoppingBag size={20} />,
                text: 'AUTO RAE-CHEM GRIT SHIELD & HEAVY DUTY 20L BUCKET WHITE - For 2 Bucket Car Wash Method + FREE SHAMPOO + WASH MIT + MICROFIBRE TOWELÎ',
              },
            ]}
          />
          <article className='prose'>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Eget lorem dolor sed viverra ipsum nunc.
              Quam nulla porttitor massa id neque. Feugiat in ante metus dictum. Dignissim diam quis
              enim lobortis. Sagittis orci a scelerisque purus semper. Tincidunt praesent semper
              feugiat nibh sed pulvinar proin gravida. Neque convallis a cras semper auctor neque
              vitae tempus. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Nunc sed
              augue lacus viverra vitae congue eu consequat ac. Sit amet consectetur adipiscing
              elit. Vel pharetra vel turpis nunc. Tempor orci dapibus ultrices in iaculis. Imperdiet
              sed euismod nisi porta lorem.
            </p>
          </article>
          <div className='h-[368px] w-[680px] pt-[40px]'>
            <img
              className='h-full w-full rounded-[12px] object-cover object-center'
              src='https://images.unsplash.com/photo-1617704548623-340376564e68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
            />
          </div>
          <article className='prose'>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Eget lorem dolor sed viverra ipsum nunc.
              Quam nulla porttitor massa id neque. Feugiat in ante metus dictum. Dignissim diam quis
              enim lobortis. Sagittis orci a scelerisque purus semper. Tincidunt praesent semper
              feugiat nibh sed pulvinar proin gravida. Neque convallis a cras semper auctor neque
              vitae tempus. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Nunc sed
              augue lacus viverra vitae congue eu consequat ac. Sit amet consectetur adipiscing
              elit. Vel pharetra vel turpis nunc. Tempor orci dapibus ultrices in iaculis. Imperdiet
              sed euismod nisi porta lorem.
            </p>
          </article>
        </div>

        <div className='flex'>
          <div className='pt-[56px]'>
            <p>Categories</p>
            <div className='pt-[12px]'>
              <Chip label='About the car' icon={<Tag size={20} />} />
            </div>
          </div>
        </div>
      </div>

      <div className='container'>
        <div className='flex w-[784px]'>
          <InlineCTA
            heading='Do you have the experties? Share your knowledge!'
            btnProps={{
              size: 'lg',
              children: 'Submit an article',
              onClick: () => {
                console.log('Clicked')
              },
            }}
          />
        </div>
      </div>

      

      <SupplierRibbon className='border-t border-N-100' />
      <Footer />
    </>
  )
}

export default Home
