import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { Button } from '@/components/atoms'
import { PageHeader } from '@/components/molecules'
import { useRouter } from 'next/router'
import { useViewport } from '@/utils'
import { searchResult } from '@/dummy-data/search-result'
import articleList from '@/dummy-data/article-list'
import { ArticleCard } from '@/components/molecules'
import { ArrowRight } from 'react-feather'
import { ContactCard } from '@/components/molecules/ContactCard'
import { Pagination } from '@/components/molecules'
import { InlineCTA } from '@/components/molecules/InlineCTA'

const Home: NextPage = () => {
  const router = useRouter()
  const { isMobile, isTablet, isDesktop } = useViewport()
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container pt-[24px] md:pt-[40px]'>
        <PageHeader
          hasSearch
          heading='Written by Tesla Owners <br />for Tesla Owners'
          description='Search through over 120 guides'
          headingClassName='text-N-800'
          descriptionClassName='text-N-600'
          btnProps={{
            onClick: (e: any) => console.log(e),
            children: 'Search',
            appearance: 'primary',
          }}
          inputProps={{
            onChange: (e: any) => console.log(e.target.value),
            placeholder: 'Need some help? Search guides to find out',
            defaultValue: '',
            size: 'lg',
          }}
        />
      </div>

      <div className='container py-[80px]'>
        <h3 className='pb-[40px] text-h3 font-700 text-N-800'>About the car</h3>

        <div className='flex gap-[48px]'>
          <div>
            <div className='flex flex-col gap-[24px] md:gap-[46px]'>
              {(searchResult || []).map((item: any, index: number) => (
                <Link href={item?.permalink} passHref key={index}>
                  <ArticleCard data={item} className='!gap-[64px]' />
                </Link>
              ))}
            </div>
            <div className='py-[80px]'>
              <InlineCTA
                heading='Do you have the experties?  Share your knowledge!'
                btnProps={{
                  children: 'Submit an article',
                  onClick: () => {
                    console.log('Clicked')
                  },
                }}
              />
            </div>
          </div>

          <div className='flex flex-col gap-[40px]'>
            <div className='most-accessed'>
              <p className='text-h4 font-600 text-N-800'>Most Accessed...</p>
              <ul className='flex flex-col gap-[8px] pt-[16px]'>
                {(articleList || []).map(({ id, text, link }: any, index: number) => (
                  <li key={id || index}>
                    <a href={link} className='text-h5 font-500 text-N-600  hover:text-B-500'>
                      {text}
                    </a>
                  </li>
                ))}
              </ul>
              <p className='flex items-center gap-[4px] pt-[16px] text-B-500'>
                <a href='#' className='text-base font-600 text-B-500 hover:text-B-600'>
                  See all most accessed (30)
                </a>
                <span>
                  <ArrowRight size={20} />
                </span>
              </p>
            </div>
            <div className='most-usefull'>
              <p className='text-h4 font-600 text-N-800'>Most Usefull...</p>
              <ul className='flex flex-col gap-[8px] pt-[16px]'>
                {(articleList || []).map(({ id, text, link }: any, index: number) => (
                  <li key={id || index}>
                    <a href={link} className='text-h5 font-500 text-N-600  hover:text-B-500'>
                      {text}
                    </a>
                  </li>
                ))}
              </ul>
              <p className='flex items-center gap-[4px] pt-[16px] text-B-500'>
                <a href='#' className='text-base font-600 text-B-500 hover:text-B-600'>
                  See all most usefull (25)
                </a>
                <span>
                  <ArrowRight size={20} />
                </span>
              </p>
            </div>
            <div className='contact-card'>
              <ContactCard
                description='Remember modifying your vehicle may invalidate part of 
                your vehicle’s warranty.<br/>
                Therefore,  be careful and check with Tesla if unsure. Also any modifications will most likely need to be 
                OK’d with your car insurance company.<br/><br/>
                To the best of our knowledge, these guides are correct and factual.
                However we take no responsibility if something does go wrong.<br/><br/>
                If you spot a mistake please ensure you alert us.'
                btnProps={{
                  label: 'Contact Us',
                  onClick: () => {
                    console.log('Clicked')
                  },
                }}
              />
            </div>
          </div>
        </div>

        <div className='w-full max-w-[784px] pt-[80px]'>
          <Pagination />
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
