import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Chip } from '@/components/atoms'
import { LinkListCard } from '@/components/molecules'
import { Tag, ShoppingBag, ArrowRight } from 'react-feather'
import { ArticleViewTopic } from '@/components/molecules/ArticleViewTopic'
import { InlineCTA } from '@/components/molecules/InlineCTA'
import { initiativeList } from '@/dummy-data/initiative-list'
import { ContactCard } from '@/components/molecules/ContactCard'
import { useViewport } from '@/utils'

const Home: NextPage = () => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='header-surface relative min-h-[358px] bg-[url(/images/004.svg)] bg-cover bg-no-repeat'>
        <div className='absolute bottom-0 h-[240px] w-full rounded-tl-[12px] rounded-tr-[12px] bg-white md:w-[75%] md:rounded-tl-none lg:bottom-0 lg:w-[60%]' />
        <div className='z-1 relative top-[116px]'>
          <ArticleViewTopic
            icon={<Tag size={16} />}
            tagText='Education & Outreach'
            heading='Fire & Rescue demonstrations and Q&A sessions'
            date='05/07/2021'
          />
        </div>
      </div>

      <div className='bg-white'>
        <div className='container flex flex-col lg:grid lg:grid-cols-[680px_367px] lg:gap-[152px]'>
          <div className='md:pt-[40px] lg:pb-[80px]'>
            <div className='flex md:gap-0 lg:gap-[48px]'>
              <div className='hidden lg:relative lg:top-[12px] lg:flex lg:h-[4px] lg:w-[56px] lg:bg-B-500' />
              <article className='prose'>
                <p>
                  We all know our cars are some of the safest on the roads but since early 2017
                  Tesla Owners UK have been attending fire and rescue teams across the UK to help
                  familiarise their teams with Tesla vehicles & demonstrate some of the functions in
                  the hope that it might help them and therefore one of us or our members in the
                  future when we really need them.
                  <br />
                  <br />
                  When Tesla vehicles were very new in the UK, many fire brigades across the UK had
                  never heard of a Tesla let alone seen one. Since then a lot has changed and all
                  fire brigades are trained on electric vehicle extraction and fires.
                  <br />
                  <br />
                  In fact, to put your mind at rest Tesla have a dedicated first responders guide
                  and have done for many years now. Also, after speaking with many fire and rescue
                  forces it was clear the majority also have access to these documents or similar on
                  iPad style devices.
                  <br />
                  <br />
                  I’m told all fire brigades within their recent training (back in 2017) have had
                  experience with EVs but still some will have never seen a Tesla or know what it
                  is, so I’m sure would be interested in a 5-minute walk around at the very least.
                </p>
              </article>
            </div>
            <div className='py-[32px] lg:py-[80px] '>
              <div className='h-[186px] w-full md:h-[376px] md:w-full lg:h-[368px] lg:w-[680px]'>
                <img
                  className='h-full w-full rounded-[12px] object-cover object-center'
                  src='https://images.unsplash.com/photo-1617704548623-340376564e68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
                />
              </div>
            </div>
            <article className='prose lg:pl-[104px]'>
              <p>
                It seems Tesla are expanding their reach to more fire services and training centres
                nationwide thanks (partially) to our work which is great news.
                <br />
                <br />
                I hope we can continue to show our support for the emergency services through Tesla
                Owners UK and help when and where we can.
                <br />
                <br />
                Thanks for everyone that has made contact with their local fire and rescue forces.
                <br />
                <br />
                However, some fire teams may still enjoy looking over your vehicle and in the past
                we’ve been most welcomed by these fire and rescue teams.
              </p>
            </article>
          </div>

          <div className='article-view-right-bar py-[40px]'>
            <div className='most-accessed'>
              <p className='text-h4 font-600 text-N-800'>
                More initiatives from Tesla Owners Club UK
              </p>
              <ul className='flex flex-col gap-[8px] pt-[16px]'>
                {(initiativeList || []).map(({ id, text, link }: any, index: number) => (
                  <li key={id || index}>
                    <a href={link} className='text-h5 font-500 text-N-600  hover:text-B-500'>
                      {text}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
