import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { PageHeaderVariant } from '@/components/molecules/PageHeaderVariant'
import { Button } from '@/components/atoms'
import { InitiativeCard } from '@/components/molecules/InitiativeCard'
import { ChartLine, Facebook, LinkedIn } from '@/icons'
import { SectionHeading } from '@/components/molecules'
import discussionList, { discussionCardList } from '@/dummy-data/discussion-list'
import { DiscussionCard } from '@/components/molecules/DiscussionCard'

const Home: NextPage = () => {
  const router = useRouter()
  const discussionList = [
    {
      id: 0,
      label: 'An ideal place for potential owners to discuss before buying',
    },
    {
      id: 1,
      label: 'Open to all, ask lots of questions from the owners on here',
    },
    {
      id: 2,
      label: 'Created by owners for owners and prospective owners',
    },
  ]

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex pt-[20px]'>
        <PageHeaderVariant
          heading='Tesla Owners <br/> Discussion Groups'
          image='https://images.unsplash.com/photo-1617788138017-80ad40651399?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
          description='The discussion groups are primarily on Facebook. Some are members only, but some are open to prospective owners.'
          commonClassName='lg:w-[30%]'
          descriptionClassName='!pt-[40px]'
          imageClassName='!h-[205px] md:!h-[248px] lg:!h-[407px] w-full'
        />
      </div>

      <div className='container'>
        {/* Regions */}
        <div className='flex flex-col items-center gap-[40px] py-[40px] md:py-[80px] lg:flex-row lg:gap-[48px]'>
          {/* image */}
          <div className='h-[200px] w-full rounded-[12px] bg-[url("https://images.unsplash.com/photo-1589718539308-169369696599?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80")] bg-cover bg-no-repeat lg:w-[576px]'>
            <div className='flex h-full flex-col justify-end rounded-b-[12px] bg-gradient-to-t from-[#000000DE] to-[#00000000] px-[28px] pb-[24px] md:flex-row md:items-end md:justify-between md:pb-[28px]'>
              <div className='flex flex-col gap-[4px]'>
                <h3 className='text-h3 font-700 text-white'>Regions</h3>
                <p className='text-base font-500 text-white'>Find local owners near to you</p>
              </div>
              <div className='flex pt-[24px] md:pt-0'>
                <Button appearance='primary' size='md'>
                  Find in your location
                </Button>
              </div>
            </div>
          </div>

          <div className='flex w-full lg:w-[576px]'>
            <p className='text-md text-N-600'>
              A major part of being a member of Tesla Owners UK is the ability to attend events –
              both National and Regional. From Track Days to Regional Meetups and visits to the
              Tesla facilities both in Europe and in the US we have you covered!
              <br /> <br />A major part of being a member of Tesla Owners UK is the ability to
              attend events – both National and Regional. From Track Days to Regional Meetups
            </p>
          </div>
        </div>
      </div>

      <div className='container pb-[40px] md:pb-[80px]'>
        {/* Discussion group section heading */}
        <SectionHeading
          overline='Official'
          heading='Facebook <br/> Discussion Groups'
          headingClassName='text-display !text-h3 lg:!text-h2 font-700 !mb-0'
          align='left'
        />

        {/* Large discussion group card */}
        <div className='flex w-full md:pt-[80px]'>
          <DiscussionCard
            size='lg'
            isWide={true}
            heading='Tesla Owners UK: Club'
            subHeading='Members only. Off-Topic posts.'
            category='Main'
            pillText='13.9K members'
            list={discussionList}
            btnProps={{
              children: 'Join the OfficialGroup',
              onClick: () => {
                console.log('Clicked')
              },
              appearance: 'secondary',
              iconBefore: <Facebook size={20} />,
            }}
            cover='https://images.unsplash.com/photo-1576221162298-3d9f04e9f661?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
          />
        </div>

        {/* All Discussion groups */}
        <div className='pt-[40px]'>
          <ul className='flex grid-cols-2 flex-col gap-[24px] md:grid md:gap-y-[40px] lg:gap-x-[48px]'>
            {(discussionCardList || []).map(
              (
                { id, heading, subHeading, category, pillText, cover, list }: any,
                index: number
              ) => (
                <li key={id || index}>
                  <DiscussionCard
                    heading={heading}
                    subHeading={subHeading}
                    pillText={pillText}
                    category={category}
                    cover={cover}
                    list={list}
                    btnProps={{
                      label: 'Join Group',
                      onClick: () => {
                        console.log('Clicked')
                      },
                      appearance: 'secondary',
                      iconBefore: <Facebook size={20} />,
                    }}
                  />
                </li>
              )
            )}
          </ul>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
