import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon, EventCard } from '@/components/sections'
import { Button, TextField } from '@/components/atoms'
import { DateCard, Pagination } from '@/components/molecules'
import { SingleEventCard } from '@/components/molecules/SingleEventCard'
import { activeEventList, inactiveEventList } from '@/dummy-data/active-event-list'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex gap-[48px] pt-[24px] md:pt-[40px]'>
        {/* Page heading */}
        <div className='flex w-[372px] flex-col gap-[40px]'>
          <h1 className='text-h1 font-700 text-N-800'>Events Calendar</h1>
          <p className='text-N-00 text-base'>
            A major part of being a member of Tesla Owners UK is the ability to attend events – both
            National and Regional. From Track Days to Regional Meetups and visits to the Tesla
            facilities both in Europe and in the US we have you covered!
          </p>
        </div>

        {/* Featured event cards */}
        <div className='flex gap-[44px]'>
          <SingleEventCard
            cover='https://images.unsplash.com/photo-1541446654331-def41325e92c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
            isFeatured='Featured'
            location=' Welcome Break Sarn Park, Sarn, Bridgend CF32 9SY, UK'
            heading='Track days'
            description='We organise several Track days per annum where you can take your own car onto the track without any prior experience as a beginnerjhwjhefk'
          />
          <SingleEventCard
            cover='https://images.unsplash.com/photo-1591134106085-8bbdc61a2ab5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80'
            isFeatured='Featured'
            location=' Welcome Break Sarn Park, Sarn, Bridgend CF32 9SY, UK'
            heading='Track days'
            description='We organise several Track days per annum where you can take your own car onto the track without any prior experience as a beginnerjhwjhefk'
          />
        </div>
      </div>

      <div className='container pt-[80px]'>
        {/* Filters */}
        <div className='flex items-center justify-between'>
          <h3 className='text-h3 font-700 text-N-800'>Upcoming events</h3>
          <div className='flex gap-[20px]'>
            <TextField placeHolder='Date range' />
            <TextField placeHolder='Location' />
            <TextField placeHolder='Event type' />
          </div>
        </div>

        {/* Active events list */}
        <div className='pt-[40px]'>
          <ul className='grid grid-cols-3 gap-x-[48px] gap-y-[40px]'>
            {(activeEventList || []).map(
              (
                { id, cover, isFeatured, month, date, appearance, eventTopic, location }: any,
                index: number
              ) => (
                <li key={id || index}>
                  <SingleEventCard
                    cover={cover}
                    isFeatured={isFeatured}
                    month={month}
                    date={date}
                    appearance={appearance}
                    eventTopic={eventTopic}
                    location={location}
                  />
                </li>
              )
            )}
          </ul>

          <div className='w-full pt-[24px] md:py-[80px]'>
            <Pagination />
          </div>
        </div>
      </div>

      {/* Past events list */}
      <div className='container pb-[80px]'>
        <div className='flex'>
          <h3 className='text-h3 font-700 text-N-800'>Past events</h3>
        </div>

        {/* Active events list */}
        <div className='pt-[40px]'>
          <ul className='grid grid-cols-3 gap-x-[48px] gap-y-[40px]'>
            {(inactiveEventList || []).map(
              (
                { id, cover, isFeatured, month, date, appearance, eventTopic, location }: any,
                index: number
              ) => (
                <li key={id || index}>
                  <SingleEventCard
                    cover={cover}
                    isFeatured={isFeatured}
                    month={month}
                    date={date}
                    appearance={appearance}
                    eventTopic={eventTopic}
                    location={location}
                  />
                </li>
              )
            )}
          </ul>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
