import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '@/components/sections'
import { PageHeader, LinkListCard } from '@/components/molecules'
import { FileText } from 'react-feather'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='pt-[80px] pb-[0px]' />

      <div className='container flex pt-[80px]'>
        <PageHeader
          hasSearch
          searchPlaceholder='Search your question here?'
          heading='Written by Tesla Owners <br />for Tesla Owners'
          description='Search through over 120 guides...'
          image='/images/page-banner-sample.png'
          headingClassName='text-N-10'
          descriptionClassName='text-N-300'
        />
      </div>

      <div className='container py-[40px]'>
        <h4 className='mb-[40px] text-h4 font-600 text-N-800'>Browse by the categories</h4>

        <div className='grid grid-cols-2 gap-[48px]'>
          <LinkListCard
            list={[
              {
                id: 0,
                textIcon: <FileText size={24} />,
                text: '100 things you never knew about your Tesla car (Model S & X edition)',
              },
              {
                id: 1,
                textIcon: <FileText size={24} />,
                text: 'Everything you learn as a new Tesla owner in winter',
              },
              {
                id: 2,
                textIcon: <FileText size={24} />,
                text: 'Tracking your Tesla from the factory to the UK',
              },
              {
                id: 3,
                textIcon: <FileText size={24} />,
                text: 'Tesla Charging Etiquette',
              },
              {
                id: 4,
                textIcon: <FileText size={24} />,
                text: 'Charging Cables and Adapters',
              },
            ]}
            heading='About the car'
            articleCount='24'
          />

          <LinkListCard
            list={[
              {
                id: 0,
                textIcon: <FileText size={24} />,
                text: '100 things you never knew about your Tesla (Model S & X edition)',
              },
              {
                id: 1,
                textIcon: <FileText size={24} />,
                text: 'Everything you learn as a new Tesla owner in winter',
              },
              {
                id: 2,
                textIcon: <FileText size={24} />,
                text: 'Tracking your Tesla from the factory to the UK',
              },
              {
                id: 3,
                textIcon: <FileText size={24} />,
                text: 'Tesla Charging Etiquette',
              },
            ]}
            heading='For new owners'
          />

          <LinkListCard
            list={[
              {
                id: 0,
                textIcon: <FileText size={24} />,
                text: '100 things you never knew about your Tesla (Model S & X edition)',
              },
              {
                id: 1,
                textIcon: <FileText size={24} />,
                text: 'Everything you learn as a new Tesla owner in winter',
              },
              {
                id: 2,
                textIcon: <FileText size={24} />,
                text: 'Tracking your Tesla from the factory to the UK',
              },
              {
                id: 3,
                textIcon: <FileText size={24} />,
                text: 'Tesla Charging Etiquette',
              },
              {
                id: 4,
                textIcon: <FileText size={24} />,
                text: 'Charging Cables and Adapters',
              },
            ]}
            heading='Upgrading, Modifying & Fixing'
            articleCount='24'
          />

          <LinkListCard
            list={[
              {
                id: 0,
                textIcon: <FileText size={24} />,
                text: '100 things you never knew about your Tesla (Model S & X edition)',
              },
              {
                id: 1,
                textIcon: <FileText size={24} />,
                text: 'Everything you learn as a new Tesla owner in winter',
              },
              {
                id: 2,
                textIcon: <FileText size={24} />,
                text: 'Tracking your Tesla from the factory to the UK',
              },
              {
                id: 3,
                textIcon: <FileText size={24} />,
                text: 'Tesla Charging Etiquette',
              },
              {
                id: 4,
                textIcon: <FileText size={24} />,
                text: 'Charging Cables and Adapters',
              },
            ]}
            heading='Charging away from home'
            articleCount='24'
          />

          <LinkListCard
            list={[
              {
                id: 0,
                textIcon: <FileText size={24} />,
                text: '100 things you never knew about your Tesla (Model S & X edition)',
              },
              {
                id: 1,
                textIcon: <FileText size={24} />,
                text: 'Everything you learn as a new Tesla owner in winter',
              },
              {
                id: 2,
                textIcon: <FileText size={24} />,
                text: 'Tracking your Tesla from the factory to the UK',
              },
              {
                id: 3,
                textIcon: <FileText size={24} />,
                text: 'Tesla Charging Etiquette',
              },
            ]}
            heading='Fear, Uncertainty & Doubt'
          />
        </div>
      </div>
    </>
  )
}

export default Home
