import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Header,
  Hero,
  EventCard,
  QuickMembership,
  QuickTestimonials,
  GuidesQuickAccess,
} from '@/components/sections'
import { PageHeader, LinkListCard } from '@/components/molecules'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='pt-[80px] pb-[0px]' />

      <div className='container flex pt-[80px]'>
        <PageHeader
          hasSearch
          searchPlaceholder='Search your question here?'
          heading='Written by Tesla Owners <br />for Tesla Owners'
          description='Search through over 120 guides...'
          image='/images/page-banner-sample.png'
          headingClassName='text-N-10'
          descriptionClassName='text-N-300'
        />
      </div>

      <div className='container py-[80px]'>
        <h4 className='text-h4 mb-[40px]'>Browser by the category</h4>

        <div className='grid grid-cols-2 gap-[48px]'>
          <LinkListCard cardHeading='About the car' articleCount='24' />
        </div>
      </div>
    </>
  )
}

export default Home
