import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam natus dolor recusandae delectus
        facere laborum fuga, sed ad praesentium non quia eligendi ab sapiente adipisci sit
        consectetur cupiditate enim deserunt.
      </div>
    </>
  )
}

export default Home
