import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Header,
  Footer,
  Hero,
  EventCard,
  QuickMembership,
  QuickTestimonials,
  GuidesQuickAccess,
  CallToAction,
  SupplierRibbon,
} from '@/components/sections'

import { Login } from '@/components/forms'
import { SectionHeading } from '@/components/molecules'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex flex-col items-center bg-[url(/images/login-bg.png)] pt-[120px]'>
        <SectionHeading heading='Tesla Owners UK Account' align='center' />

        <Login />
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
