import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Header,
  Footer,
  Hero,
  EventCard,
  QuickMembership,
  QuickTestimonials,
  GuidesQuickAccess,
  CallToAction,
  SupplierRibbon,
} from '@/components/sections'

import { Login } from '@/components/forms'
import { SectionHeading } from '@/components/molecules'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex flex-col items-center rounded-[12px] bg-[url(/images/hero-pattern.svg)] py-[32px] lg:pt-[40px] lg:pb-[80px]'>
        <SectionHeading heading='Tesla Owners UK Account' align='center' />

        <div className='w-full pt-[8px] md:w-[448px] md:pt-[16px] lg:w-[448px] lg:pt-[16px]'>
          <Login />
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
