import CN from 'classnames'
import Link from 'next/link'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Button } from '@/components/atoms'
import { MemberCard } from '@/components/molecules/MemberCard'
import { ArrowRightCircle } from 'react-feather'
import { DashboardMenu } from '@/components/molecules/DashboardMenu'
import { useViewport } from '@/utils'

const Home: NextPage = () => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()
  const recentOrdersList = [
    {
      id: '0',
      product: `Tesla Owners UK Annual Supporter Fee + Official Supporter Welcome Pack
      Sold By: Tesla Owners UK `,
      url: '#',
      itemsCount: '1',
      price: '£35.00 / day',
      subTotal: '£35.00 / day',
      total: '£35.00 / day',
    },
  ]

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex gap-[48px] pt-[40px] pb-[40px] lg:pb-[80px]'>
        <div className='dashboard-menu hidden lg:flex'>
          <div className='w-full'>
            <DashboardMenu />
          </div>
        </div>

        <div className='flex w-full flex-col'>
          <div className='flex justify-between'>
            <div className='lg:w-full'>
              <div>
                <h4 className='text-h4 font-600 text-N-800'>Membership</h4>
                <div className='pt-[32px]'>
                  <div className='text-base font-500 text-N-800'>Membership details</div>
                  <div className='flex gap-[32px] pt-[16px] text-base'>
                    <div className='flex flex-col gap-[16px]'>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Name</p>
                        <p>Tim Fernando</p>
                      </div>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Email</p>
                        <p>tim@example.com</p>
                      </div>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Type</p>
                        <p>Supporter membership</p>
                      </div>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>ID</p>
                        <p>5867</p>
                      </div>
                    </div>
                    <div className='flex flex-col gap-[16px]'>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Status</p>
                        <p className='font-600 text-G-500'>Active</p>
                      </div>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Start date</p>
                        <p>20/10/2021</p>
                      </div>
                      <div className='flex'>
                        <p className='w-[104px] text-md font-500 text-N-600'>Expires on</p>
                        <p className='font-600 text-B-500'>20/10/2021</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='pt-[32px]'>
                  <Link href='#'>
                    <Button
                      className='text-base !font-600 !text-N-800'
                      iconAfter={<i className='ri-arrow-right-line text-lg' />}
                      appearance='link'>
                      Supporter membership agreement
                    </Button>
                  </Link>
                </div>

                <div className='pt-[32px]'>
                  <Link href='#'>
                    <Button
                      className='text-base !font-600 !text-N-800'
                      appearance='secondary'
                      view='solid'>
                      Cancel membership
                    </Button>
                  </Link>
                </div>
              </div>
            </div>

            <div className='flex h-[400px] flex-col items-center'>
              <MemberCard
                name='Tim Fernando'
                email='tim@example.com'
                type='Supporter membership'
                expireDate='20/10/2021'
              />
              <p className='py-[24px] text-center text-md text-N-600'>
                Android? Install this{' '}
                <a target='_blank' href='' className='underline'>
                  app
                </a>{' '}
                & follow this{' '}
                <a target='_blank' href='' className='underline'>
                  guide
                </a>
                .
              </p>
            </div>
          </div>

          <div className='pt-[80px]'>
            <div className='text-base font-500 text-N-800'>Subscription totals</div>
            <div className='scrollbar-py-[12px] scrollbar-track-rounded-full scrollbar-thumb-rounded-full w-full overflow-auto overflow-y-scroll pt-[24px]  scrollbar-thin scrollbar-track-N-100 scrollbar-thumb-N-300 md:pt-[24px] lg:pt-[16px]'>
              <div className='flex w-[1000px] flex-col gap-[16px] overflow-auto md:w-[960px] lg:w-[unset]'>
                <div className='grid grid-cols-[8fr_2fr_2fr_2fr] gap-[16px] bg-N-50 py-[4px] pl-[16px] text-md font-500 text-N-600'>
                  <div>Product</div>
                  <div>No. of items</div>
                  <div>Total</div>
                  <div>Actions</div>
                </div>
              </div>
              <div>
                <ul className='flex w-[1000px] flex-col gap-[16px] overflow-auto bg-white text-base md:w-[960px] lg:w-[unset]'>
                  {recentOrdersList.map(({ id, url, product, itemsCount, price }, index) => (
                    <li
                      key={id || index}
                      className='grid grid-cols-[8fr_2fr_2fr_2fr] gap-[16px] border-b-[1px] border-N-200 py-[20px] pl-[16px]'>
                      <p className='font-400 text-N-600'>{product}</p>
                      <p className='font-400 text-N-600'>{itemsCount}</p>
                      <p>{price}</p>
                      <div className='flex gap-[16px]'>
                        <a
                          target='_blank'
                          href={url}
                          className='font-600 text-N-800 hover:text-B-500'>
                          View
                        </a>
                      </div>
                    </li>
                  ))}
                </ul>
                <ul className='bg-white'>
                  <li className='grid grid-cols-[5fr_2fr] border-b-[1px] border-N-200 py-[20px] pl-[16px]'>
                    <p className='text-md font-600 text-N-600'>Sub total:</p>
                    <p className='text-base font-600'>£35.00 / day</p>
                  </li>
                  <li className='tex-md grid grid-cols-[5fr_2fr] py-[20px] pl-[16px]'>
                    <p className='text-md font-600 text-N-600'>Total:</p>
                    <p className='text-base font-600'>£35.00 / day</p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <SupplierRibbon className='border-t border-N-100' />
      <Footer />
    </>
  )
}

export default Home
