import { useState } from 'react'
import CN from 'classnames'
import Link from 'next/link'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Button } from '@/components/atoms'
import { MemberCard } from '@/components/molecules/MemberCard'
import { ArrowRightCircle } from 'react-feather'
import { DashboardMenu } from '@/components/molecules/DashboardMenu'
import { useViewport } from '@/utils'
import { PurchasesOrders } from '@/components/sections/PurchasesOrders'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = () => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()

  const [activeTab, setActiveTab] = useState('orders')
  const recentOrdersList = [
    {
      id: '0',
      orderNumber: '#39155',
      label: 'Pending payment',
      url: '#',
      date: '21/10/2021',
      itemsCount: '1',
      price: '£35',
      isCompleted: false,
      isPending: true,
    },
    {
      id: '1',
      orderNumber: '#39155',
      label: 'Delivered',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: false,
      isPending: false,
    },
    {
      id: '2',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '3',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '4',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '5',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '6',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '7',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
    {
      id: '8',
      orderNumber: '#39155',
      label: 'Order completed',
      url: '#',
      itemsCount: '1',
      price: '£35',
      date: '21/10/2021',
      isCompleted: true,
      isPending: false,
    },
  ]

  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container flex gap-[48px] py-[40px] md:pb-[80px] lg:pb-[80px]'>
          <div className='dashboard-menu hidden lg:flex'>
            <div className='w-full'>
              <DashboardMenu />
            </div>
          </div>

          <div className='flex w-full flex-col'>
            <h4 className='pb-[24px] text-h4 font-600 text-N-800'>Purchases</h4>
            <div className='flex gap-[12px] border-b-[1px]'>
              <Link href='#'>
                <Button
                  className='mb-[16px] text-base font-600'
                  view={activeTab === 'orders' ? 'outline' : 'solid'}
                  appearance='ghost'
                  onClick={() => setActiveTab('orders')}>
                  Orders
                </Button>
              </Link>
              <Link href='#'>
                <Button
                  className='mb-[16px] text-base font-600'
                  appearance='ghost'
                  onClick={() => setActiveTab('booking')}>
                  Booking
                </Button>
              </Link>
            </div>
            <div className='flex flex-col'>
              {activeTab === 'orders' && <PurchasesOrders />}
              {activeTab === 'booking' && <PurchasesOrders />}
            </div>

            <div className='pt-[24px] md:pt-[16px] lg:pt-[16px]'>
              <Link href='#'>
                <Button iconAfter={<i className='ri-arrow-right-line text-lg' />} appearance='link'>
                  Load more
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
