import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'

import { SectionHeading } from '@/components/molecules'
import { PasswordReset } from '@/components/forms/PasswordReset'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container pb-[40px] md:pb-[80px]'>
        <div className='flex flex-col items-center rounded-[12px] bg-[url(/images/patterns/background.svg)] bg-cover bg-no-repeat py-[32px] lg:py-[112px]'>
          <SectionHeading
            headingClassName='md:!text-h3 !text-h4 !font-600 md:!font-700 !mb-0'
            heading='Tesla Owners UK Account'
            align='center'
          />

          <div className='g:w-[448px] w-full px-[16px] pt-[32px] md:w-[448px] md:px-0'>
            <PasswordReset />
          </div>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
