import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'

import { SectionHeading } from '@/components/molecules'
import { PasswordReset } from '@/components/forms/PasswordReset'
import { ApprovalPopup } from '@/components/molecules/ApprovalPopup'
import CN from 'classnames'
import { Common as CommonLayout } from '@/components/layouts'

const Page: NextPage = () => {
  const [activeTab, setActiveTab] = useState('password-reset')
  return (
    <>
      <Head>
        <title>Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout>
        <div className='container pb-[40px] md:pb-[80px]'>
          <div className='flex flex-col items-center rounded-[8px] bg-[url(/images/patterns/background.svg)] bg-cover bg-no-repeat py-[32px] lg:py-[112px]'>
            <SectionHeading
              headingClassName='md:!text-h3 !text-h4 !font-600 md:!font-700 !mb-0'
              heading='Tesla Owners UK Account'
              align='center'
            />

            <div
              className={CN('w-full px-[16px] pt-[32px] md:w-[448px] md:px-0 lg:w-[448px]', {
                '': activeTab === 'password-reset',
                'flex': activeTab !== 'password-reset',
              })}>
              <PasswordReset />
            </div>

            <div
              className={CN('w-full px-[16px] pt-[32px] md:w-[448px] md:px-0 lg:w-[448px]', {
                '': activeTab === 'pop-up',
                'hidden': activeTab !== 'pop-up',
              })}>
              <ApprovalPopup description='We have sent password reset link. Check your email' />
            </div>
          </div>
        </div>
      </CommonLayout>
    </>
  )
}

export default Page
