import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { ShopCard } from '@/components/molecules/ShopCard'
import { Button, CheckBox, FieldGroup, Radio, TextField } from '@/components/atoms'
import shopList from '@/dummy-data/shop-list'
import { Pagination } from '@/components/molecules'
import { useViewport } from '@/utils'
import { ArrowRight, Delete, Filter, ShoppingBag, Trash } from 'react-feather'
import { ShoppingCard } from '@/components/molecules/ShoppingCard'
import { PriceCard } from '@/components/molecules/PriceCard'

const Home: NextPage = () => {
  const { isMobile, isTablet, isDesktop } = useViewport()
  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container pt-[16px] pb-[80px]'>
        <h1 className='text-h3 font-700 text-N-800'>Shopping Cart (3)</h1>

        <div className='flex justify-between'>
          <div className='flex flex-col gap-[96px] pt-[40px]'>
            <ShoppingCard
              image='/shop-item.png'
              heading='CHAdeMO adapter rental - Available for paid supporters only (Model S/X only)'
              shopName='England - Milton Keynes'
              price='£35.00'
              priceDetails='1X £35.00 / year'
            />
            <ShoppingCard
              image='/shop-item.png'
              heading='CHAdeMO adapter rental - Available for paid supporters only (Model S/X only)'
              shopName='England - Milton Keynes'
              price='£35.00'
              priceDetails='1X £35.00 / year'
            />
            <ShoppingCard
              image='/shop-item.png'
              heading='CHAdeMO adapter rental - Available for paid supporters only (Model S/X only)'
              shopName='England - Milton Keynes'
              price='£35.00'
              priceDetails='1X £35.00 / year'
            />
            <ShoppingCard
              image='/shop-item.png'
              heading='CHAdeMO adapter rental - Available for paid supporters only (Model S/X only)'
              shopName='England - Milton Keynes'
              price='£35.00'
              priceDetails='1X £35.00 / year'
            />
          </div>

          <div className='flex h-full'>
            <PriceCard
              subTotal='£35.00'
              shippingCost='£10.00'
              discount='£0.00'
              gst='£60.50'
              total='£12,231.76'
              isDiscount={true}
            />
          </div>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
