import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { PageHeaderVariant } from '@/components/molecules/PageHeaderVariant'
import { Button } from '@/components/atoms'
import { InitiativeCard } from '@/components/molecules/InitiativeCard'
import { ChartLine, Facebook, LinkedIn } from '@/icons'
import { SectionHeading } from '@/components/molecules'
import discussionList, { discussionCardList } from '@/dummy-data/discussion-list'
import { DiscussionCard } from '@/components/molecules/DiscussionCard'
import { ArrowLeft, ArrowRight } from 'react-feather'

const Home: NextPage = () => {
  const router = useRouter()
  const discussionList = [
    {
      id: 0,
      label: 'An ideal place for potential owners to discuss before buying',
    },
    {
      id: 1,
      label: 'Open to all, ask lots of questions from the owners on here',
    },
    {
      id: 2,
      label: 'Created by owners for owners and prospective owners',
    },
  ]

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='container flex pt-[20px] pb-[80px]'>
        <PageHeaderVariant
          heading='Suppliers'
          image='https://images.unsplash.com/photo-1617788138017-80ad40651399?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'
          description='The Tesla Owners UK Directory showcases the <br/> best Tesla related products and services from <br/> across the UK.'
          commonClassName='lg:w-[30%] !gap-0'
          descriptionClassName='text-md !pt-[16px]'
          imageClassName='!h-[205px] md:!h-[248px] lg:!h-[407px] w-full'
          metaData='Trusted suppliers <br/> network across United <br/> Kingdom'
          metaDataNumber='500+'
          btnProps={{
            label: 'Search suppliers',
            onClick: () => {
              console.log('Clicked')
            },
            appearance: 'secondary',
            className: 'w-[208px]',
          }}
        />
      </div>

      {/* Partners Banner */}
      <div className='bg-[url("/images/patterns/003.svg")] bg-cover bg-no-repeat'>
        <div className='container py-[80px]'>
          <SectionHeading
            overline='tesla owners club uk'
            heading='Key Partners'
            headingClassName='text-display !text-h3 lg:!text-h2 font-700 !mb-0'
            align='center'
          />

          {/* Partners */}
          <div className='grid grid-cols-4 gap-x-[48px] gap-y-[40px] py-[48px]'>
            <img
              src='/images/partners/partner-001.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-002.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-003.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-004.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-005.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-004.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-007.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
            <img
              src='/images/partners/partner-008.png'
              className='h-[120px] w-[264px] object-cover object-center'
            />
          </div>

          <div className='flex justify-center'>
            <Button appearance='ghost' iconAfter={<ArrowRight size={20} />}>
              Become a key partner
            </Button>
          </div>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
