import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import {
  Tag,
  ShoppingBag,
  ArrowRight,
  ArrowLeft,
  Globe,
  Map,
  MapPin,
  Phone,
  Mail,
  Bookmark,
  Compass,
} from 'react-feather'
import { InlineCTA } from '@/components/molecules/InlineCTA'
import { useViewport } from '@/utils'
import { SupplierAboutHeader } from '@/components/molecules/SupplierAboutHeader'
import { Button, TextField } from '@/components/atoms'
import { SupplierDetailsTabs } from '@/components/sections/SupplierDetailsTabs'

const Home: NextPage = () => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()

  const renderGraphic = () => {
    return (
      <div className='flex md:w-full lg:w-[784px]'>
        <InlineCTA
          heading='Do you have the experties? Share your knowledge!'
          btnProps={{
            size: 'lg',
            children: 'Submit an article',
            onClick: () => {
              console.log('Clicked')
            },
          }}
        />
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      <div className='header-surface relative min-h-[356px] bg-[url(/images/004.svg)] bg-cover bg-no-repeat'>
        <div className='container py-[50px]'>
          <Button
            appearance='ghost'
            iconBefore={<ArrowLeft size={20} />}
            className='h-[unset] px-0 hover:text-B-500'>
            Back to Search results
          </Button>
        </div>
        <div className='absolute bottom-0 h-[228px] w-full rounded-tl-[12px] bg-N-10 md:w-[75%] md:rounded-tl-none lg:w-[904px]' />
        <div className='z-1 container relative py-[32px] pr-[32px]'>
          <SupplierAboutHeader
            icon={<Tag size={16} />}
            category='Home & Work Charger Installer, Solar / Powerwall / Electrician'
            heading='JPS Renewable Energy'
            isVerified={true}
            isFeatured={true}
            image='/images/suppliers.png'
          />
        </div>
      </div>

      <div className='container flex flex-col gap-[24px] pt-[24px] pb-[40px] md:gap-[48px] md:pt-[40px] md:pb-[80px] lg:flex-row'>
        <div className='lg:w-[784px]'>
          <div className='border-b border-b-N-200'>
            <SupplierDetailsTabs />
          </div>
          <div>Add the widget</div>
        </div>

        <div className='flex flex-col md:flex-row-reverse md:gap-[24px] lg:flex-col lg:gap-0 lg:w-[368px]'>
          {/* Contact details */}
          <div className='flex flex-col gap-[16px]'>
            {/* Address */}
            <div className='flex items-center gap-[8px]'>
              <div className='h-[32px] w-[32px] rounded-full bg-N-100 px-[8px] py-[8px] text-N-800'>
                <MapPin size={16} />
              </div>
              <p className='text-md font-500 text-N-600'>
                11 Phoenix Park Parkwood Industrial Estate Maidstone Kent ME15 9XN
              </p>
            </div>

            {/* Phone number */}
            <div className='flex items-center gap-[8px]'>
              <div className='h-[32px] w-[32px] rounded-full bg-N-100 px-[8px] py-[8px] text-N-800'>
                <Phone size={16} />
              </div>
              <p className='text-md font-500 text-N-600'>0300 3033136</p>
            </div>

            {/* Email */}
            <div className='flex items-center gap-[8px]'>
              <div className='h-[32px] w-[32px] rounded-full bg-N-100 px-[8px] py-[8px] text-N-800'>
                <Mail size={16} />
              </div>
              <p className='text-md font-500 text-N-600'>enquiries@jpsgroup.uk</p>
            </div>

            {/* Website*/}
            <div className='flex items-center gap-[8px]'>
              <div className='h-[32px] w-[32px] rounded-full bg-N-100 px-[8px] py-[8px] text-N-800'>
                <Globe size={16} />
              </div>
              <p className='text-md font-500 text-N-600'>https://jpsrenewableenergy.co.uk</p>
            </div>

            <div className='pt-[8px] lg:pt-[40px]'>
              <Button
                iconAfter={<Bookmark size={20} />}
                appearance='primary'
                className='w-full lg:w-[unset]'>
                Bookmark
              </Button>
            </div>
          </div>

          {/* Map */}
          <div className='flex flex-col gap-[24px] pt-[24px] md:pt-0 lg:gap-[40px] lg:pt-[40px]'>
            <img
              src='https://images.unsplash.com/photo-1461183479101-6c14cd5299c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'
              className='h-[343px] w-full rounded-[12px] object-cover object-center md:h-[368px] md:w-[368px]  '
            />
            <div className='flex flex-col gap-[16px]'>
              <TextField placeHolder='Your location' />
              <div className='flex'>
                <Button
                  iconAfter={<Compass size={20} />}
                  appearance='primary'
                  className='w-full lg:w-[unset]'>
                  Get directions
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
