import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header, Footer, SupplierRibbon } from '@/components/sections'
import { useRouter } from 'next/router'
import { Tag, ArrowLeft, Globe, MapPin, Phone, Mail, Bookmark, Compass } from 'react-feather'
import { useViewport } from '@/utils'
import { SupplierAboutHeader } from '@/components/molecules/SupplierAboutHeader'
import { Button, TextField } from '@/components/atoms'
import { SupplierDetailsTabs } from '@/components/sections/SupplierDetailsTabs'
import { SupplierAboutSideBar } from '@/components/sections/SupplierAboutSideBar'
import { RelatedListingsSideBar } from '@/components/sections/RelatedListingsSideBar'

const Home: NextPage = () => {
  const router = useRouter()
  const { isDesktop, isMobile, isTablet } = useViewport()
  const [activeTab, setActiveTab] = useState('about')

  return (
    <>
      <Head>
        <title>Karapincha UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header className='py-[24px]' />

      {/* <div className='header-surface relative min-h-[356px] bg-[url(/images/004.svg)] bg-cover bg-no-repeat'>
        <div className='container py-[50px]'>
          <Button
            appearance='ghost'
            iconBefore={<ArrowLeft size={20} />}
            className='h-[unset] px-0 hover:text-B-500'>
            Back to Search results
          </Button>
        </div>
        <div className='absolute bottom-0 h-[228px] w-full rounded-tl-[12px] bg-N-10 md:w-[75%] md:rounded-tl-none lg:w-[904px]' />
        <div className='z-1 container relative py-[32px] pr-[32px]'>
          <SupplierAboutHeader
            icon={<Tag size={16} />}
            category='Home & Work Charger Installer, Solar / Powerwall / Electrician'
            heading='JPS Renewable Energy'
            isVerified={true}
            isFeatured={true}
            image='/images/suppliers.png'
          />
        </div>
      </div> */}

      <div className='container flex flex-col gap-[24px] pt-[24px] pb-[40px] md:gap-[48px] md:pt-[40px] md:pb-[80px] lg:flex-row'>
        <div className='lg:w-[784px]'>
          <div className=''>
            <SupplierDetailsTabs onChange={(tab: any) => setActiveTab(tab)} />
          </div>
        </div>

        <div className='flex'>
          {activeTab === 'about' && <SupplierAboutSideBar />}
          {activeTab === 'related-listings' && <RelatedListingsSideBar />}
        </div>
      </div>

      <SupplierRibbon />
      <Footer />
    </>
  )
}

export default Home
