import type { NextPage } from 'next'
import Head from 'next/head'
import { FileText, Mail } from 'react-feather'
import {
  MembershipCardPreview,
  SupporterBenefits,
  TestimonialCarousel,
  Faq,
} from '@/components/sections'
import { PageHeader, ContactCta, SectionHeading } from '@/components/molecules'
import { testimonials } from '@/dummy-data/testimonials'
import { Common as CommonLayout } from '@/components/layouts'
import { getMembershipPage } from '../../lib/graphql'

const Page: NextPage = ({ pageData }: any) => {
  const { supporterMemberBlock, freeMemberBlock }: any = pageData.membershipBlock.blockMembership

  const { faq, staticPageHeader } = pageData.page
  const { testimonials } = pageData

  console.log(testimonials)

  return (
    <>
      <Head>
        <title>{staticPageHeader?.heading || 'Join the club'} - Tesla Owners UK</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <CommonLayout className='pb-0'>
        <div className='container pt-[40px]'>
          <SectionHeading
            overline={staticPageHeader?.overline}
            heading={staticPageHeader?.heading}
            headingClassName='!text-h1 !mb-[16px]'
            description={staticPageHeader?.description}
            align='center'
            descriptionClassName='max-w-[490px] !text-md !font-500'
          />
        </div>

        <div className='container max-w-[992px] py-[24px] md:py-[80px] lg:py-[80px]'>
          <MembershipCardPreview
            data={{ supporterMemberBlock, freeMemberBlock }}
            isMembershipPage
          />
        </div>

        <SupporterBenefits
          data={supporterMemberBlock}
          className='py-[24px] md:py-[80px] lg:py-[80px]'
        />

        <TestimonialCarousel
          className='pt-[24px] pb-[16px] md:pt-[80px]'
          list={testimonials.nodes || []}
        />

        <Faq className='pt-[20px] pb-[24px] md:pb-[80px] lg:pb-[80px]' list={faq.faqList} />

        <ContactCta
          heading='Still have questions? <br />Contact us'
          icon={<Mail size={32} />}
          email='members@teslaowners.org.uk'
        />
      </CommonLayout>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const pageData = await getMembershipPage()

  return {
    props: {
      pageData,
    },
    revalidate: 1,
  }
}

export default Page
